spring:
  application:
    name: pagamento-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/pagamento}
    username: ${SPRING_DATASOURCE_USERNAME:pagamento}
    password: ${SPRING_DATASOURCE_PASSWORD:pagamento}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8180/realms/microservices

server:
  port: 8083
  error:
    include-message: always

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_BASE_URL:http://localhost:9411}/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

info:
  app:
    name: pagamento service

logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"

pagamento:
  # Ajuste para forcar erros e observar o circuit breaker do vendas-service abrindo.
  # valor de 0 (nenhum) a 1 (100%).
  failRate: 0.1
  delayMs: 0
