spring:
  application:
    name: vendas-service
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 1000
            readTimeout: 2000
  zipkin:
    baseUrl: http://localhost:9411

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

info:
  app:
    name: vendas service

resilience4j:
  circuitbreaker:
    instances:
      estoque:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      pagamento:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"