version: "3.9"

services:
  discovery:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    container_name: discovery
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - ms-net

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    depends_on:
      discovery:
        condition: service_healthy
    environment:
      - EUREKA_URI=http://discovery:8761/eureka
      - ZIPKIN_BASE_URL=http://host.docker.internal:9411
    ports:
      - "8080:8080"
    networks:
      - ms-net

  vendas-service:
    build:
      context: ./vendas-service
      dockerfile: Dockerfile
    container_name: vendas-service
    depends_on:
      discovery:
        condition: service_healthy
    environment:
      - EUREKA_URI=http://discovery:8761/eureka
      - ZIPKIN_BASE_URL=http://host.docker.internal:9411
    ports:
      - "8081:8081"
    networks:
      - ms-net

  estoque-service:
    build:
      context: ./estoque-service
      dockerfile: Dockerfile
    container_name: estoque-service
    depends_on:
      discovery:
        condition: service_healthy
    environment:
      - EUREKA_URI=http://discovery:8761/eureka
      - ZIPKIN_BASE_URL=http://host.docker.internal:9411
    ports:
      - "8082:8082"
    networks:
      - ms-net

  pagamento-service:
    build:
      context: ./pagamento-service
      dockerfile: Dockerfile
    container_name: pagamento-service
    depends_on:
      discovery:
        condition: service_healthy
    environment:
      - EUREKA_URI=http://discovery:8761/eureka
      - ZIPKIN_BASE_URL=http://host.docker.internal:9411
    ports:
      - "8083:8083"
    networks:
      - ms-net

  frete-service:
    build:
      context: ./frete-service
      dockerfile: Dockerfile
    container_name: frete-service
    depends_on:
      discovery:
        condition: service_healthy
    environment:
      - EUREKA_URI=http://discovery:8761/eureka
      - ZIPKIN_BASE_URL=http://host.docker.internal:9411
    ports:
      - "8084:8084"
    networks:
      - ms-net

networks:
  ms-net:
    driver: bridge
