spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: vendas-service
          uri: lb://vendas-service
          predicates:
            - Path=/vendas/**
        - id: estoque-service
          uri: lb://estoque-service
          predicates:
            - Path=/estoque/**
        - id: pagamento-service
          uri: lb://pagamento-service
          predicates:
            - Path=/pagamento/**
        - id: frete-service
          uri: lb://frete-service
          predicates:
            - Path=/frete/**
        - id: transportadora-service
          uri: lb://transportadora-service
          predicates:
            - Path=/transportadora/**
        - id: notificacao-service
          uri: lb://notificacao-service
          predicates:
            - Path=/notificacao/**
        - id: whoami-vendas
          uri: lb://vendas-service
          predicates:
            - Path=/whoami/vendas
          filters:
            - SetPath=/vendas/whoami
        - id: whoami-estoque
          uri: lb://estoque-service
          predicates:
            - Path=/whoami/estoque
          filters:
            - SetPath=/estoque/whoami
        - id: whoami-pagamento
          uri: lb://pagamento-service
          predicates:
            - Path=/whoami/pagamento
          filters:
            - SetPath=/pagamento/whoami
        - id: whoami-frete
          uri: lb://frete-service
          predicates:
            - Path=/whoami/frete
          filters:
            - SetPath=/frete/whoami
        - id: whoami-transportadora
          uri: lb://transportadora-service
          predicates:
            - Path=/whoami/transportadora
          filters:
            - SetPath=/transportadora/whoami
        - id: whoami-notificacao
          uri: lb://notificacao-service
          predicates:
            - Path=/whoami/notificacao
          filters:
            - SetPath=/notificacao/whoami
management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_BASE_URL:http://localhost:9411}/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

info:
  app:
    name: api gateway

logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${random.value}
